sudo: required

language: Go

services:
  - docker
jobs:
  include:
  - arch : amd64
    script:
        - make check
        - make -C smoke_tests
  - arch : arm64
    script:
        - docker pull alpine:latest
        - chmod a+x docker_run.sh
        - bash ./docker_run.sh
